import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const postsDir = path.join(root, "_posts");
const outputFile = path.join(root, "src", "generated", "posts.js");

const files = await collectMarkdown(postsDir);
const posts = [];

for (const file of files) {
  const raw = await readFile(file, "utf8");
  const { data, content } = parseFrontMatter(raw);
  if (data.hidden === true || data.hidden === "true") continue;

  const filename = path.basename(file, ".md");
  const dateMatch = filename.match(/^(\d{4}-\d{2}-\d{2})-(.+)$/);
  const date = data.date || dateMatch?.[1] || "";
  const slugSource = dateMatch?.[2] || filename;

  posts.push({
    title: data.title || slugSource,
    subtitle: data.subtitle || "",
    author: data.author || "Xinzhe Zhou",
    date,
    slug: slugify(`${date}-${slugSource}`),
    tags: normalizeTags(data.tags),
    content: content.trim()
  });
}

posts.sort((a, b) => b.date.localeCompare(a.date));

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(
  outputFile,
  `// This file is generated by scripts/build-content.mjs.\nexport const posts = ${JSON.stringify(posts, null, 2)};\n`,
  "utf8"
);

console.log(`Generated ${posts.length} posts at ${path.relative(root, outputFile)}`);

async function collectMarkdown(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const result = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      result.push(...(await collectMarkdown(fullPath)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      result.push(fullPath);
    }
  }

  return result;
}

function parseFrontMatter(raw) {
  if (!raw.startsWith("---")) {
    return { data: {}, content: raw };
  }

  const end = raw.indexOf("\n---", 3);
  if (end < 0) {
    return { data: {}, content: raw };
  }

  const frontMatter = raw.slice(3, end).trim();
  const content = raw.slice(end + 4);
  return { data: parseYamlSubset(frontMatter), content };
}

function parseYamlSubset(source) {
  const data = {};
  const lines = source.split("\n");
  let currentKey = null;

  for (const rawLine of lines) {
    const line = rawLine.replace(/\t/g, "  ");
    if (!line.trim()) continue;

    const listItem = line.match(/^\s+-\s+(.+)$/);
    if (listItem && currentKey) {
      if (!Array.isArray(data[currentKey])) data[currentKey] = [];
      data[currentKey].push(cleanValue(listItem[1]));
      continue;
    }

    const pair = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!pair) continue;

    currentKey = pair[1];
    const value = pair[2];
    data[currentKey] = value === "" ? [] : cleanValue(value);
  }

  return data;
}

function cleanValue(value) {
  const trimmed = value.trim();
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function normalizeTags(value) {
  if (Array.isArray(value)) return value.map(String).filter(Boolean);
  if (typeof value === "string" && value) return value.split(",").map((item) => item.trim()).filter(Boolean);
  return [];
}

function slugify(value) {
  return value
    .normalize("NFKD")
    .replace(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}
